services:

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: calculations
      POSTGRES_USER: calculations
      POSTGRES_PASSWORD: calculationspass
    ports:
      - "5432:5432"

