version: "3.9"
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: calculations
      POSTGRES_USER: calculations
      POSTGRES_PASSWORD: calculationspass
    ports:
      - "5432:5432"

