services:

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: calculations
      POSTGRES_USER: calculations
      POSTGRES_PASSWORD: calculationspass
    ports:
      - "5432:5432"
      
  scheduledcalculations:
    build: ./scheduledcalculations
    ports:
      - "8080:8080"
    depends_on:
      - db

  webapp:
    build: ./webapp
    ports:
      - "3000:3000"
    depends_on:
      - scheduledcalculations
